Test the layer with a random input and check if the output shows the desired behavior.

In [17]:
from si.neural_networks.layers import DropoutLayer
import numpy as np

In [18]:
# Dropout rate (50%)
probability = 0.5  
# Random input data (3 samples, 3 features)
input_data = np.random.randn(3, 3)  

# Create the Dropout layer
dropout_layer = DropoutLayer(probability=probability)

# Testing during Training:
print("Training:")
output_train = dropout_layer.forward_propagation(input_data, training=True)

# Display the input and the output after applying Dropout
print("\nInput:")
print(input_data)
print("\nOutput with Dropout (during training):")
print(output_train)
print("\nApplied Mask (0 values represent deactivated neurons):")
print(dropout_layer.mask)

Training:

Input:
[[ 0.2601804  -0.59984995  0.78609914]
 [ 0.01152746  1.5452114   1.08075114]
 [ 0.25134991  0.15358925  1.03383439]]

Output with Dropout (during training):
[[ 0.52036079 -0.          0.        ]
 [ 0.02305492  0.          0.        ]
 [ 0.50269981  0.          0.        ]]

Applied Mask (0 values represent deactivated neurons):
[[1 0 0]
 [1 0 0]
 [1 0 0]]


In [19]:
# Testing during Inference:
print("\nInference:")
output_infer = dropout_layer.forward_propagation(input_data, training=False)

# Display the input and the output during inference (no changes, no dropout)
print("\nInput:")
print(input_data)
print("\nOutput with Dropout (no changes during inference):")
print(output_infer)


Inference:

Input:
[[ 0.2601804  -0.59984995  0.78609914]
 [ 0.01152746  1.5452114   1.08075114]
 [ 0.25134991  0.15358925  1.03383439]]

Output with Dropout (no changes during inference):
[[ 0.2601804  -0.59984995  0.78609914]
 [ 0.01152746  1.5452114   1.08075114]
 [ 0.25134991  0.15358925  1.03383439]]


As we can see, the function behaves as expected. During training, after applying the mask, the output contains both deactivated (0) and activated neurons. 
However, during inference, no neurons are deactivated. The sizes of the input and output remain consistent.