• 1.1) In this exercise, we will use the iris dataset. Load
the "iris.csv" using the appropriate method for this file
type (use the new functions from the package).

In [4]:
import numpy as np
import pandas as pd

path = r"C:\Users\tiago\OneDrive\Documentos\GitHub\si\datasets\iris\iris.csv"

# 1. Carregar o dataset 
iris_df = pd.read_csv(path)

# 2. Converter o DataFrame pandas para um array NumPy
iris_array = iris_df.to_numpy()

# 3. Mostrar as primeiras linhas para ver como os dados estão organizados
print(iris_array[:5])

[[5.1 3.5 1.4 0.2 'Iris-setosa']
 [4.9 3.0 1.4 0.2 'Iris-setosa']
 [4.7 3.2 1.3 0.2 'Iris-setosa']
 [4.6 3.1 1.5 0.2 'Iris-setosa']
 [5.0 3.6 1.4 0.2 'Iris-setosa']]


• 1.2) Select the penultimate independent variable.
What is the dimension of the resulting array?

In [5]:
# 1. Selecionar a penúltima variável independente (penúltima coluna)
penultimate_column = iris_array[:, -2]  

# 2. Verificar a dimensão do array resultante
print("Penúltima coluna (variável independente):", penultimate_column)
print("Dimensão do array:", penultimate_column.shape)

Penúltima coluna (variável independente): [0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 0.2 0.2 0.1 0.1 0.2 0.4 0.4 0.3
 0.3 0.3 0.2 0.4 0.2 0.5 0.2 0.2 0.4 0.2 0.2 0.2 0.2 0.4 0.1 0.2 0.1 0.2
 0.2 0.1 0.2 0.2 0.3 0.3 0.2 0.6 0.4 0.3 0.2 0.2 0.2 0.2 1.4 1.5 1.5 1.3
 1.5 1.3 1.6 1.0 1.3 1.4 1.0 1.5 1.0 1.4 1.3 1.4 1.5 1.0 1.5 1.1 1.8 1.3
 1.5 1.2 1.3 1.4 1.4 1.7 1.5 1.0 1.1 1.0 1.2 1.6 1.5 1.6 1.5 1.3 1.3 1.3
 1.2 1.4 1.2 1.0 1.3 1.2 1.3 1.3 1.1 1.3 2.5 1.9 2.1 1.8 2.2 2.1 1.7 1.8
 1.8 2.5 2.0 1.9 2.1 2.0 2.4 2.3 1.8 2.2 2.3 1.5 2.3 2.0 2.0 1.8 2.1 1.8
 1.8 1.8 2.1 1.6 1.9 2.0 2.2 1.5 1.4 2.3 2.4 1.8 1.8 2.1 2.4 2.3 1.9 2.3
 2.5 2.3 1.9 2.0 2.3 1.8]
Dimensão do array: (150,)


• 1.3) Select the last 10 samples from the iris dataset.
What is the mean of the last 10 samples for each
independent variable/feature?

In [6]:
# 1. Seleciona as últimas 10 linhas e todas as colunas, exceto a última (variável dependente)
last_10_samples = iris_array[-10:, :-1] 

# 2. Calcular a média de cada variável independente (por coluna)
mean_last_10_samples = np.mean(last_10_samples, axis=0)

# 3. Mostrar o resultado
print("Últimas 10 amostras:\n", last_10_samples)
print("\nMédia das últimas 10 amostras para cada variável independente:\n", mean_last_10_samples)

Últimas 10 amostras:
 [[6.7 3.1 5.6 2.4]
 [6.9 3.1 5.1 2.3]
 [5.8 2.7 5.1 1.9]
 [6.8 3.2 5.9 2.3]
 [6.7 3.3 5.7 2.5]
 [6.7 3.0 5.2 2.3]
 [6.3 2.5 5.0 1.9]
 [6.5 3.0 5.2 2.0]
 [6.2 3.4 5.4 2.3]
 [5.9 3.0 5.1 1.8]]

Média das últimas 10 amostras para cada variável independente:
 [6.450000000000001 3.0300000000000002 5.33 2.1700000000000004]


• 1.4) Select all samples from the dataset with values
less than or equal to 6 for all independent
variables/features. How many samples do you obtain?

In [7]:
# 1. Selecionar as variáveis independentes (todas as colunas exceto a última)
independent_variables = iris_array[:, :-1]

# 2. Aplicar a condição: Selecionar amostras onde todos os valores são <= 6
samples_with_values_leq_6 = independent_variables[np.all(independent_variables <= 6, axis=1)]

# 3. Contar o número de amostras que atendem a essa condição
num_samples = samples_with_values_leq_6.shape[0]

print("Número de amostras com todas as variáveis <= 6:", num_samples)

Número de amostras com todas as variáveis <= 6: 89


• 1.5) Select all samples with a class/label different
from 'Iris-setosa'. How many samples do you obtain

In [8]:
# 1. Selecionar a coluna de classes (última coluna)
labels = iris_array[:, -1]  

# 2. Filtrar as amostras cuja classe seja diferente de 'Iris-setosa'
non_setosa_samples = iris_array[labels != 'Iris-setosa']

# 3. Contar o número de amostras que atendem a essa condição
num_non_setosa = non_setosa_samples.shape[0]

# 4. Mostrar o resultado
print("Número de amostras com classe diferente de 'Iris-setosa':", num_non_setosa)

Número de amostras com classe diferente de 'Iris-setosa': 100
