• 1.1) In this exercise, we will use the iris dataset. Load
the "iris.csv" using the appropriate method for this file
type (use the new functions from the package).

In [1]:
import numpy as np
import pandas as pd

path = r"C:\Users\tiago\OneDrive\Documentos\GitHub\si\datasets\iris\iris.csv"

iris_df = pd.read_csv(path)
iris_array = iris_df.to_numpy()
print(iris_array[:5])

[[5.1 3.5 1.4 0.2 'Iris-setosa']
 [4.9 3.0 1.4 0.2 'Iris-setosa']
 [4.7 3.2 1.3 0.2 'Iris-setosa']
 [4.6 3.1 1.5 0.2 'Iris-setosa']
 [5.0 3.6 1.4 0.2 'Iris-setosa']]


• 1.2) Select the penultimate independent variable.
What is the dimension of the resulting array?

In [2]:
# 1. Select the penultimate independent variable (second to last column)
penultimate_column = iris_array[:, -2]  

# 2. Check the dimension of the resulting array
print("Penultimate column (independent variable):", penultimate_column)
print("Dimension of the array:", penultimate_column.shape)

Penultimate column (independent variable): [0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 0.2 0.2 0.1 0.1 0.2 0.4 0.4 0.3
 0.3 0.3 0.2 0.4 0.2 0.5 0.2 0.2 0.4 0.2 0.2 0.2 0.2 0.4 0.1 0.2 0.1 0.2
 0.2 0.1 0.2 0.2 0.3 0.3 0.2 0.6 0.4 0.3 0.2 0.2 0.2 0.2 1.4 1.5 1.5 1.3
 1.5 1.3 1.6 1.0 1.3 1.4 1.0 1.5 1.0 1.4 1.3 1.4 1.5 1.0 1.5 1.1 1.8 1.3
 1.5 1.2 1.3 1.4 1.4 1.7 1.5 1.0 1.1 1.0 1.2 1.6 1.5 1.6 1.5 1.3 1.3 1.3
 1.2 1.4 1.2 1.0 1.3 1.2 1.3 1.3 1.1 1.3 2.5 1.9 2.1 1.8 2.2 2.1 1.7 1.8
 1.8 2.5 2.0 1.9 2.1 2.0 2.4 2.3 1.8 2.2 2.3 1.5 2.3 2.0 2.0 1.8 2.1 1.8
 1.8 1.8 2.1 1.6 1.9 2.0 2.2 1.5 1.4 2.3 2.4 1.8 1.8 2.1 2.4 2.3 1.9 2.3
 2.5 2.3 1.9 2.0 2.3 1.8]
Dimension of the array: (150,)


• 1.3) Select the last 10 samples from the iris dataset.
What is the mean of the last 10 samples for each
independent variable/feature?

In [3]:
# 1. Select the last 10 rows and all columns except the last (dependent variable)
last_10_samples = iris_array[-10:, :-1] 

# 2. Calculate the mean of each independent variable (per column)
mean_last_10_samples = np.mean(last_10_samples, axis=0)

# 3. Show the result
print("Last 10 samples:\n", last_10_samples)
print("\nMean of the last 10 samples for each independent variable:\n", mean_last_10_samples)

Last 10 samples:
 [[6.7 3.1 5.6 2.4]
 [6.9 3.1 5.1 2.3]
 [5.8 2.7 5.1 1.9]
 [6.8 3.2 5.9 2.3]
 [6.7 3.3 5.7 2.5]
 [6.7 3.0 5.2 2.3]
 [6.3 2.5 5.0 1.9]
 [6.5 3.0 5.2 2.0]
 [6.2 3.4 5.4 2.3]
 [5.9 3.0 5.1 1.8]]

Mean of the last 10 samples for each independent variable:
 [6.450000000000001 3.0300000000000002 5.33 2.1700000000000004]


• 1.4) Select all samples from the dataset with values
less than or equal to 6 for all independent
variables/features. How many samples do you obtain?

In [4]:
# 1. Select the independent variables (all columns except the last)
independent_variables = iris_array[:, :-1]

# 2. Apply the condition: Select samples where all values are <= 6
samples_with_values_leq_6 = independent_variables[np.all(independent_variables <= 6, axis=1)]

# 3. Count the number of samples that meet this condition
num_samples = samples_with_values_leq_6.shape[0]

print("Number of samples with all variables <= 6:", num_samples)

Number of samples with all variables <= 6: 89


• 1.5) Select all samples with a class/label different
from 'Iris-setosa'. How many samples do you obtain

In [5]:
# 1. Select the class column (last column)
labels = iris_array[:, -1]  

# 2. Filter samples whose class is different from 'Iris-setosa'
non_setosa_samples = iris_array[labels != 'Iris-setosa']

# 3. Count the number of samples that meet this condition
num_non_setosa = non_setosa_samples.shape[0]

# 4. Display the result
print("Number of samples with class different from 'Iris-setosa':", num_non_setosa)

Number of samples with class different from 'Iris-setosa': 100
