In [13]:
import numpy as np
import pandas as pd

• 1.1) In this exercise, we will use the iris dataset. Load
the "iris.csv" using the appropriate method for this file
type (use the new functions from the package).

In [15]:
from si.io.csv_file import read_csv

path = r"C:\Users\tiago\OneDrive\Documentos\GitHub\si\datasets\iris\iris.csv"

In [16]:
iris_data = read_csv(path, sep=",")
print(type(iris_data))

<class 'si.data.dataset.Dataset'>


In [17]:
iris_df = pd.DataFrame(data=iris_data.X, columns=iris_data.features)
iris_df.head()

feat_0 feat_1 feat_2 feat_3       feat_4
0    5.1    3.5    1.4    0.2  Iris-setosa
1    4.9    3.0    1.4    0.2  Iris-setosa
2    4.7    3.2    1.3    0.2  Iris-setosa
3    4.6    3.1    1.5    0.2  Iris-setosa
4    5.0    3.6    1.4    0.2  Iris-setosa

• 1.2) Select the penultimate independent variable.
What is the dimension of the resulting array?

In [25]:
# 1. Select the penultimate independent variable (third to last column, because the last column is the dependent variable)
penultimate_column = iris_data.X[:, -3]  

# 2. Check the dimension of the resulting array
print("Penultimate column (independent variable):", penultimate_column)
print("Dimension of the array:", penultimate_column.shape)

Penultimate column (independent variable): [1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 1.5 1.6 1.4 1.1 1.2 1.5 1.3 1.4
 1.7 1.5 1.7 1.5 1.0 1.7 1.9 1.6 1.6 1.5 1.4 1.6 1.6 1.5 1.5 1.4 1.5 1.2
 1.3 1.5 1.3 1.5 1.3 1.3 1.3 1.6 1.9 1.4 1.6 1.4 1.5 1.4 4.7 4.5 4.9 4.0
 4.6 4.5 4.7 3.3 4.6 3.9 3.5 4.2 4.0 4.7 3.6 4.4 4.5 4.1 4.5 3.9 4.8 4.0
 4.9 4.7 4.3 4.4 4.8 5.0 4.5 3.5 3.8 3.7 3.9 5.1 4.5 4.5 4.7 4.4 4.1 4.0
 4.4 4.6 4.0 3.3 4.2 4.2 4.2 4.3 3.0 4.1 6.0 5.1 5.9 5.6 5.8 6.6 4.5 6.3
 5.8 6.1 5.1 5.3 5.5 5.0 5.1 5.3 5.5 6.7 6.9 5.0 5.7 4.9 6.7 4.9 5.7 6.0
 4.8 4.9 5.6 5.8 6.1 6.4 5.6 5.1 5.6 6.1 5.6 5.5 4.8 5.4 5.6 5.1 5.1 5.9
 5.7 5.2 5.0 5.2 5.4 5.1]
Dimension of the array: (150,)


• 1.3) Select the last 10 samples from the iris dataset.
What is the mean of the last 10 samples for each
independent variable/feature?

In [31]:
# 1. Select the last 10 rows and all columns except the last (dependent variable)
last_10_samples = iris_data.X[-10:, :-1] 

# 2. Calculate the mean of each independent variable (per column)
mean_last_10_samples = np.mean(last_10_samples, axis=0)

print("Last 10 samples:\n", last_10_samples)
print("\nMean of the last 10 samples for each independent variable:\n", mean_last_10_samples)

Last 10 samples:
 [[6.7 3.1 5.6 2.4]
 [6.9 3.1 5.1 2.3]
 [5.8 2.7 5.1 1.9]
 [6.8 3.2 5.9 2.3]
 [6.7 3.3 5.7 2.5]
 [6.7 3.0 5.2 2.3]
 [6.3 2.5 5.0 1.9]
 [6.5 3.0 5.2 2.0]
 [6.2 3.4 5.4 2.3]
 [5.9 3.0 5.1 1.8]]

Mean of the last 10 samples for each independent variable:
 [6.450000000000001 3.0300000000000002 5.33 2.1700000000000004]


• 1.4) Select all samples from the dataset with values
less than or equal to 6 for all independent
variables/features. How many samples do you obtain?

In [37]:
# 1. Select the independent variables (all columns except the last)
independent_variables = iris_data.X[:, :-1]

# 2. Apply the condition: Select samples where all values are <= 6
samples_with_values_leq_6 = independent_variables[np.all(independent_variables <= 6, axis=1)]

# 3. Count the number of samples that meet this condition
num_samples = samples_with_values_leq_6.shape[0]

print("Number of samples with all variables <= 6:", num_samples)

Number of samples with all variables <= 6: 89


• 1.5) Select all samples with a class/label different
from 'Iris-setosa'. How many samples do you obtain

In [35]:
labels = iris_data.X[:, -1]  

# 1. Filter samples whose class is different from 'Iris-setosa'
non_setosa_samples = iris_data.X[labels != 'Iris-setosa']

# 2. Count the number of samples that meet this condition
num_non_setosa = non_setosa_samples.shape[0]

print("Number of samples with class different from 'Iris-setosa':", num_non_setosa)

Number of samples with class different from 'Iris-setosa': 100
